### ISSUE TITLE
InvalidOperationException when PlotView ancestry changes

### ISSUE THREAD

**Issue by carlreinke** [oxyplot/oxyplot#1834]
### Steps to reproduce

1. Place a `OxyPlot.SkiaSharp.Wpf.PlotView` in an AvalonDock tab.
2. Float the tab (right-click tab and click "Float").

[Example project](https://github.com/oxyplot/oxyplot/files/7765844/WpfTest.zip) provided.

Platform: Windows 10
.NET version: .NET 4.8

### Expected behaviour

No exception is thrown.

### Actual behaviour

```
System.InvalidOperationException: The specified Visual is not an ancestor of this Visual.
    at System.Windows.Media.Visual.TrySimpleTransformToAncestor(Visual ancestor, Boolean inverse, GeneralTransform& generalTransform, Matrix& simpleTransform)
    at System.Windows.Media.Visual.TransformToAncestor(Visual ancestor)
    at OxyPlot.SkiaSharp.Wpf.OxySKElement.OnRender(DrawingContext drawingContext)
...
```

**Comment by VisualMelon** [comment]
Are you able to test this with the develop branch? I'm not certain, but this sort of things should have been addressed by https://github.com/oxyplot/oxyplot/pull/1797

**Comment by carlreinke** [comment]
I did not test with the develop branch.  I did test with [2.1.0-unstable.1467](https://www.myget.org/feed/oxyplot/package/nuget/OxyPlot.SkiaSharp.Wpf/2.1.0-unstable.1467), and the problem still existed.

**Comment by VisualMelon** [comment]
Sorry, completely missed that this was Skia;  #1799 should address this (tested).

**Comment by VisualMelon** [comment]
Closing now that #1799 is merged. Feel free to re-open if you believe it is not fixed in the develop branch (unstable.1468).
